[package]
name = "out-reference"
version = "0.2.0"
authors = ["RustyYato <rustyyato@gmail.com>"]
edition = "2018"

description = "out references"
license = "MIT"

[features]

default = ["std"]

std = []
nightly = []

[dependencies]
